// Code generated by MockGen. DO NOT EDIT.
// Source: c:\go\microservice\audit-service\repository\audit_repository.go
//
// Generated by this command:
//
//	mockgen -source=c:\go\microservice\audit-service\repository\audit_repository.go -destination=c:\go\microservice\audit-service\mock\mock_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "microservice/audit-service/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuditRepository is a mock of AuditRepository interface.
type MockAuditRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditRepositoryMockRecorder is the mock recorder for MockAuditRepository.
type MockAuditRepositoryMockRecorder struct {
	mock *MockAuditRepository
}

// NewMockAuditRepository creates a new mock instance.
func NewMockAuditRepository(ctrl *gomock.Controller) *MockAuditRepository {
	mock := &MockAuditRepository{ctrl: ctrl}
	mock.recorder = &MockAuditRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditRepository) EXPECT() *MockAuditRepositoryMockRecorder {
	return m.recorder
}

// GetListAuditLog mocks base method.
func (m *MockAuditRepository) GetListAuditLog(ctx context.Context, page, show int, itemId, itemType string) ([]model.AuditLog, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListAuditLog", ctx, page, show, itemId, itemType)
	ret0, _ := ret[0].([]model.AuditLog)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetListAuditLog indicates an expected call of GetListAuditLog.
func (mr *MockAuditRepositoryMockRecorder) GetListAuditLog(ctx, page, show, itemId, itemType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListAuditLog", reflect.TypeOf((*MockAuditRepository)(nil).GetListAuditLog), ctx, page, show, itemId, itemType)
}

// Save mocks base method.
func (m *MockAuditRepository) Save(ctx context.Context, log *model.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAuditRepositoryMockRecorder) Save(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAuditRepository)(nil).Save), ctx, log)
}
